apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: chatbot:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: model-storage
          mountPath: /models/qwen
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "24Gi"
            cpu: "8"
          requests:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: model-storage
        hostPath:
          path: ~/huggingface_models/Qwen-Qwen2.5-7B-Instruct/
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000